/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'vw_stock_his.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'vw_stock_his.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./vw_stock_his.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("codart").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.vwStockHis",
    options: {
        tableName: "vw_stock_his",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "codart": {
            type: Seq.CHAR(16),
            field: "codart"
        },
        "codcol": {
            type: Seq.CHAR(16),
            field: "codcol"
        },
        "ori": {
            type: Seq.INTEGER,
            field: "ori"
        },
        "des": {
            type: Seq.INTEGER,
            field: "des"
        },
        "fem": {
            type: Seq.DATEONLY,
            field: "fem"
        },
        "id": {
            type: Seq.INTEGER,
            field: "id"
        },
        "tipo": {
            type: Seq.INTEGER,
            field: "tipo"
        },
        "nombre": {
            type: Seq.CHAR(50),
            field: "nombre"
        },
        "can": {
            type: Seq.DECIMAL,
            field: "can"
        },
        "pza": {
            type: Seq.BIGINT,
            field: "pza"
        }
    },
    relations: []
};