/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'vw_stxdepxartxcol.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'vw_stxdepxartxcol.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./vw_stxdepxartxcol.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("deposito").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.vwStxdepxartxcol",
    options: {
        tableName: "vw_stxdepxartxcol",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "deposito": {
            type: Seq.INTEGER,
            field: "deposito"
        },
        "articulo": {
            type: Seq.INTEGER,
            field: "articulo"
        },
        "color": {
            type: Seq.INTEGER,
            field: "color"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        },
        "lot": {
            type: Seq.CHAR(3),
            field: "lot"
        },
        "amount": {
            type: Seq.DECIMAL,
            field: "amount"
        },
        "reservedamount": {
            type: Seq.DECIMAL,
            field: "reservedamount"
        },
        "itemdata": {
            type: Seq.INTEGER,
            field: "itemdata"
        }
    },
    relations: []
};