/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ssecur_procedure.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ssecur_procedure.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ssecur_procedure.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("nro").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.ssecurProcedure",
    options: {
        tableName: "ssecur_procedure",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "nro": {
            type: Seq.INTEGER,
            field: "nro",
            primaryKey: true,
            allowNull: false,
            unique: "sproc__nokey"
        },
        "progno": {
            type: Seq.INTEGER,
            field: "progno"
        },
        "name": {
            type: Seq.STRING(30),
            field: "name"
        },
        "generaldoorno": {
            type: Seq.INTEGER,
            field: "generaldoorno"
        },
        "generaloverride": {
            type: Seq.INTEGER,
            field: "generaloverride"
        },
        "insertdoorno": {
            type: Seq.INTEGER,
            field: "insertdoorno"
        },
        "insertoverride": {
            type: Seq.INTEGER,
            field: "insertoverride"
        },
        "changedoorno": {
            type: Seq.INTEGER,
            field: "changedoorno"
        },
        "changeoverride": {
            type: Seq.INTEGER,
            field: "changeoverride"
        },
        "deletedoorno": {
            type: Seq.INTEGER,
            field: "deletedoorno"
        },
        "deleteoverride": {
            type: Seq.INTEGER,
            field: "deleteoverride"
        },
        "viewdoorno": {
            type: Seq.INTEGER,
            field: "viewdoorno"
        },
        "viewoverride": {
            type: Seq.INTEGER,
            field: "viewoverride"
        }
    },
    relations: []
};