/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'viewpiezasagrxmts.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'viewpiezasagrxmts.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./viewpiezasagrxmts.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("unitload").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.viewpiezasagrxmts",
    options: {
        tableName: "viewpiezasagrxmts",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "unitload": {
            type: Seq.INTEGER,
            field: "unitload"
        },
        "itemdata": {
            type: Seq.INTEGER,
            field: "itemdata"
        },
        "amount": {
            type: Seq.DECIMAL(8, 3),
            field: "amount"
        },
        "cantidad": {
            type: Seq.BIGINT,
            field: "cantidad"
        }
    },
    relations: []
};