/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'cuadricula.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'cuadricula.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./cuadricula.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("clidirCuadriculaFkeys").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.cuadricula",
    options: {
        tableName: "cuadricula",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "cuadricula_pkey"
        },
        "nombre": {
            type: Seq.CHAR(50),
            field: "nombre"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.clidir",
        schema: "public",
        table: "clidir",
        source: "generator",
        details: {
            as: "clidirCuadriculaFkeys",
            foreignKey: "cuadricula",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.expresos",
        schema: "public",
        table: "expresos",
        source: "generator",
        details: {
            as: "expresosCuadriculaFkeys",
            foreignKey: "cuadricula",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.expresos",
        schema: "public",
        table: "expresos",
        source: "generator",
        details: {
            as: "relatedClidirCuadriculaFkeyExpresos",
            foreignKey: "cuadricula",
            otherKey: "expreso",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.clientes",
        schema: "public",
        table: "clientes",
        source: "generator",
        details: {
            as: "relatedClidirCuadriculaFkeyIdclis",
            foreignKey: "cuadricula",
            otherKey: "idcli",
            through: "clidir",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.provincia",
        schema: "public",
        table: "provincia",
        source: "generator",
        details: {
            as: "relatedClidirCuadriculaFkeyProvs",
            foreignKey: "cuadricula",
            otherKey: "prov",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.provincia",
        schema: "public",
        table: "provincia",
        source: "generator",
        details: {
            as: "relatedExpresosCuadriculaFkeyProvs",
            foreignKey: "cuadricula",
            otherKey: "prov",
            through: "expresos",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};