/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'vw_stk_disp_var.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'vw_stk_disp_var.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./vw_stk_disp_var.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("catNom").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.vwStkDispVar",
    options: {
        tableName: "vw_stk_disp_var",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "catNom": {
            type: Seq.CHAR(30),
            field: "cat_nom"
        },
        "artCod": {
            type: Seq.DECIMAL,
            field: "art_cod"
        },
        "artNom": {
            type: Seq.CHAR(50),
            field: "art_nom"
        },
        "colCod": {
            type: Seq.CHAR(16),
            field: "col_cod"
        },
        "colNom": {
            type: Seq.CHAR(50),
            field: "col_nom"
        },
        "uniStk": {
            type: Seq.INTEGER,
            field: "uni_stk"
        },
        "uniPed": {
            type: Seq.INTEGER,
            field: "uni_ped"
        }
    },
    relations: []
};