/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ssecur_call.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ssecur_call.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ssecur_call.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("description").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.ssecurCall",
    options: {
        tableName: "ssecur_call",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "description": {
            type: Seq.STRING(100),
            field: "description"
        },
        "nro": {
            type: Seq.INTEGER,
            field: "nro",
            primaryKey: true,
            allowNull: false,
            unique: "scall__nokey"
        },
        "procno": {
            type: Seq.INTEGER,
            field: "procno"
        },
        "request": {
            type: Seq.INTEGER,
            field: "request"
        },
        "userno": {
            type: Seq.INTEGER,
            field: "userno"
        },
        "date": {
            type: Seq.INTEGER,
            field: "date"
        },
        "time": {
            type: Seq.INTEGER,
            field: "time"
        },
        "fileno": {
            type: Seq.INTEGER,
            field: "fileno"
        },
        "primarykey": {
            type: Seq.INTEGER,
            field: "primarykey"
        },
        "accessdenied": {
            type: Seq.INTEGER,
            field: "accessdenied"
        },
        "requestcancelled": {
            type: Seq.INTEGER,
            field: "requestcancelled"
        }
    },
    relations: []
};