/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ssecur_door.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ssecur_door.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ssecur_door.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedDgrpno").onDelete = 'CASCADE'; 
util.getAttribute("nro").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.ssecurDoor",
    options: {
        tableName: "ssecur_door",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "nro": {
            type: Seq.INTEGER,
            field: "nro",
            primaryKey: true,
            allowNull: false,
            unique: "sdoor__nokey"
        },
        "dgrpno": {
            type: Seq.INTEGER,
            field: "dgrpno",
            unique: "dgrpdesckey",
            references: "public.ssecurDoorgroup",
            referencesKey: "dgrpno"
        },
        "equate": {
            type: Seq.STRING(30),
            field: "equate",
            allowNull: false,
            unique: "equatekey"
        },
        "description": {
            type: Seq.STRING(60),
            field: "description",
            allowNull: false,
            unique: "dgrpdesckey"
        },
        "freeze": {
            type: Seq.INTEGER,
            field: "Freeze"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.ssecurDoorgroup",
        schema: "public",
        table: "ssecur_doorgroup",
        source: "generator",
        details: {
            as: "relatedDgrpno",
            foreignKey: "dgrpno",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};