/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'expresos.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'expresos.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./expresos.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("clidirExpresoFkeys").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.expresos",
    options: {
        tableName: "expresos",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "expresos_pkey"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        },
        "dir": {
            type: Seq.CHAR(50),
            field: "dir"
        },
        "localidad": {
            type: Seq.CHAR(50),
            field: "localidad"
        },
        "codpos": {
            type: Seq.CHAR(8),
            field: "codpos"
        },
        "prov": {
            type: Seq.INTEGER,
            field: "prov",
            references: "public.provincia",
            referencesKey: "prov"
        },
        "tel": {
            type: Seq.CHAR(50),
            field: "tel"
        },
        "cuit": {
            type: Seq.CHAR(11),
            field: "cuit"
        },
        "horario": {
            type: Seq.CHAR(50),
            field: "horario"
        },
        "cuadricula": {
            type: Seq.INTEGER,
            field: "cuadricula",
            references: "public.cuadricula",
            referencesKey: "cuadricula"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.clidir",
        schema: "public",
        table: "clidir",
        source: "generator",
        details: {
            as: "clidirExpresoFkeys",
            foreignKey: "expreso",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.cuadricula",
        schema: "public",
        table: "cuadricula",
        source: "generator",
        details: {
            as: "relatedCuadricula",
            foreignKey: "cuadricula",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.provincia",
        schema: "public",
        table: "provincia",
        source: "generator",
        details: {
            as: "relatedProv",
            foreignKey: "prov",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.cuadricula",
        schema: "public",
        table: "cuadricula",
        source: "generator",
        details: {
            as: "relatedClidirExpresoFkeyCuadriculas",
            foreignKey: "expreso",
            otherKey: "cuadricula",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.clientes",
        schema: "public",
        table: "clientes",
        source: "generator",
        details: {
            as: "relatedClidirExpresoFkeyIdclis",
            foreignKey: "expreso",
            otherKey: "idcli",
            through: "clidir",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.provincia",
        schema: "public",
        table: "provincia",
        source: "generator",
        details: {
            as: "relatedClidirExpresoFkeyProvs",
            foreignKey: "expreso",
            otherKey: "prov",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};