/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'vw_st_xdep_xart_xcolor.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'vw_st_xdep_xart_xcolor.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./vw_st_xdep_xart_xcolor.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("deposito").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.vwStXdepXartXcolor",
    options: {
        tableName: "vw_st_xdep_xart_xcolor",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "deposito": {
            type: Seq.INTEGER,
            field: "deposito"
        },
        "articulo": {
            type: Seq.CHAR(16),
            field: "articulo"
        },
        "color": {
            type: Seq.CHAR(16),
            field: "color"
        },
        "cantidad": {
            type: Seq.INTEGER,
            field: "cantidad"
        },
        "metros": {
            type: Seq.INTEGER,
            field: "metros"
        },
        "unidad": {
            type: Seq.CHAR(3),
            field: "unidad"
        }
    },
    relations: []
};