/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'area.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'area.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./area.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkStoragelocationAreas").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.area",
    options: {
        tableName: "area",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "area_pkey"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.storagelocation",
        schema: "public",
        table: "storagelocation",
        source: "generator",
        details: {
            as: "fkStoragelocationAreas",
            foreignKey: "area",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.storagelocation",
        schema: "public",
        table: "storagelocation",
        source: "generator",
        details: {
            as: "storagelocationAreaFkeys",
            foreignKey: "area",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.deposito",
        schema: "public",
        table: "deposito",
        source: "generator",
        details: {
            as: "relatedFkStoragelocationAreaDepositos",
            foreignKey: "area",
            otherKey: "deposito",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.zona",
        schema: "public",
        table: "zona",
        source: "generator",
        details: {
            as: "relatedFkStoragelocationAreaZonas",
            foreignKey: "area",
            otherKey: "zona",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.area",
        schema: "public",
        table: "area",
        source: "generator",
        details: {
            as: "relatedFkStoragelocationAreaAreas",
            foreignKey: "area",
            otherKey: "area",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.area",
        schema: "public",
        table: "area",
        source: "generator",
        details: {
            as: "relatedStoragelocationAreaFkeyAreas",
            foreignKey: "area",
            otherKey: "area",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.deposito",
        schema: "public",
        table: "deposito",
        source: "generator",
        details: {
            as: "relatedStoragelocationAreaFkeyDepositos",
            foreignKey: "area",
            otherKey: "deposito",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.zona",
        schema: "public",
        table: "zona",
        source: "generator",
        details: {
            as: "relatedStoragelocationAreaFkeyZonas",
            foreignKey: "area",
            otherKey: "zona",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.calle",
        schema: "public",
        table: "calle",
        source: "generator",
        details: {
            as: "relatedFkStoragelocationAreaCalles",
            foreignKey: "area",
            otherKey: "calle",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.calle",
        schema: "public",
        table: "calle",
        source: "generator",
        details: {
            as: "relatedStoragelocationAreaFkeyCalles",
            foreignKey: "area",
            otherKey: "calle",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.zona",
        schema: "public",
        table: "zona",
        source: "generator",
        details: {
            as: "relatedFkStoragelocationAreaZonas",
            foreignKey: "area",
            otherKey: "zona",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.zona",
        schema: "public",
        table: "zona",
        source: "generator",
        details: {
            as: "relatedStoragelocationAreaFkeyZonas",
            foreignKey: "area",
            otherKey: "zona",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};