/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ssecur_user.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ssecur_user.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ssecur_user.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("nro").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.ssecurUser",
    options: {
        tableName: "ssecur_user",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "nro": {
            type: Seq.INTEGER,
            field: "nro",
            primaryKey: true,
            allowNull: false,
            unique: "suser__nokey"
        },
        "groupflag": {
            type: Seq.INTEGER,
            field: "groupflag",
            unique: "groupnamekey"
        },
        "lastname": {
            type: Seq.STRING(25),
            field: "lastname",
            allowNull: false,
            unique: "usernamekey"
        },
        "firstname": {
            type: Seq.STRING(15),
            field: "firstname",
            unique: "usernamekey"
        },
        "password": {
            type: Seq.STRING(20),
            field: "password",
            allowNull: false
        },
        "slevel": {
            type: Seq.INTEGER,
            field: "slevel",
            allowNull: false
        },
        "passwordsize": {
            type: Seq.INTEGER,
            field: "passwordsize"
        },
        "passwordmaxage": {
            type: Seq.INTEGER,
            field: "passwordmaxage"
        },
        "passworddate": {
            type: Seq.INTEGER,
            field: "passworddate"
        },
        "passwordtime": {
            type: Seq.INTEGER,
            field: "passwordtime"
        },
        "logondate": {
            type: Seq.INTEGER,
            field: "logondate"
        },
        "logontime": {
            type: Seq.INTEGER,
            field: "logontime"
        },
        "failures": {
            type: Seq.INTEGER,
            field: "failures"
        },
        "slocked": {
            type: Seq.INTEGER,
            field: "slocked"
        },
        "email": {
            type: Seq.CHAR(128),
            field: "email"
        }
    },
    relations: []
};