/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'provincia.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'provincia.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./provincia.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("clidirProvFkeys").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.provincia",
    options: {
        tableName: "provincia",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "provincia_pkey"
        },
        "nom": {
            type: Seq.CHAR(25),
            field: "nom",
            allowNull: false
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.clidir",
        schema: "public",
        table: "clidir",
        source: "generator",
        details: {
            as: "clidirProvFkeys",
            foreignKey: "prov",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.expresos",
        schema: "public",
        table: "expresos",
        source: "generator",
        details: {
            as: "expresosProvFkeys",
            foreignKey: "prov",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.cuadricula",
        schema: "public",
        table: "cuadricula",
        source: "generator",
        details: {
            as: "relatedClidirProvFkeyCuadriculas",
            foreignKey: "prov",
            otherKey: "cuadricula",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.expresos",
        schema: "public",
        table: "expresos",
        source: "generator",
        details: {
            as: "relatedClidirProvFkeyExpresos",
            foreignKey: "prov",
            otherKey: "expreso",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.clientes",
        schema: "public",
        table: "clientes",
        source: "generator",
        details: {
            as: "relatedClidirProvFkeyIdclis",
            foreignKey: "prov",
            otherKey: "idcli",
            through: "clidir",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.cuadricula",
        schema: "public",
        table: "cuadricula",
        source: "generator",
        details: {
            as: "relatedExpresosProvFkeyCuadriculas",
            foreignKey: "prov",
            otherKey: "cuadricula",
            through: "expresos",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};