/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'viewstockxarticulocolor.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'viewstockxarticulocolor.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./viewstockxarticulocolor.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("area").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.viewstockxarticulocolor",
    options: {
        tableName: "viewstockxarticulocolor",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "area": {
            type: Seq.INTEGER,
            field: "area"
        },
        "articulo": {
            type: Seq.INTEGER,
            field: "articulo"
        },
        "color": {
            type: Seq.INTEGER,
            field: "color"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        },
        "amount": {
            type: Seq.DECIMAL,
            field: "amount"
        },
        "reservedamount": {
            type: Seq.DECIMAL,
            field: "reservedamount"
        }
    },
    relations: []
};