/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ssecur_access.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ssecur_access.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ssecur_access.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("userno").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.ssecurAccess",
    options: {
        tableName: "ssecur_access",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "userno": {
            type: Seq.INTEGER,
            field: "userno",
            primaryKey: true,
            allowNull: false,
            unique: "sacc__userdoorkey"
        },
        "doorno": {
            type: Seq.INTEGER,
            field: "doorno",
            primaryKey: true,
            allowNull: false,
            unique: "sacc__userdoorkey"
        },
        "denyflag": {
            type: Seq.INTEGER,
            field: "denyflag"
        }
    },
    relations: []
};