/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'stockunit.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'stockunit.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./stockunit.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedItemdatum").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.stockunit",
    options: {
        tableName: "stockunit",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "stockunit_pkey"
        },
        "itemdata": {
            type: Seq.INTEGER,
            field: "itemdata",
            allowNull: false,
            references: "public.itemdata",
            referencesKey: "itemdata"
        },
        "amount": {
            type: Seq.DECIMAL(8, 3),
            field: "amount"
        },
        "reservedamount": {
            type: Seq.DECIMAL(8, 3),
            field: "reservedamount"
        },
        "unitload": {
            type: Seq.INTEGER,
            field: "unitload",
            references: "public.unitload",
            referencesKey: "unitload"
        },
        "lote": {
            type: Seq.INTEGER,
            field: "lote"
        },
        "suorigen": {
            type: Seq.INTEGER,
            field: "suorigen"
        },
        "estado": {
            type: Seq.INTEGER,
            field: "estado"
        },
        "serie": {
            type: Seq.CHAR(24),
            field: "serie"
        },
        "fplanilla": {
            type: Seq.DATE,
            field: "fplanilla"
        },
        "empresa": {
            type: Seq.INTEGER,
            field: "empresa"
        },
        "deposito": {
            type: Seq.INTEGER,
            field: "deposito"
        },
        "pack": {
            type: Seq.INTEGER,
            field: "pack"
        },
        "lot": {
            type: Seq.CHAR(3),
            field: "lot"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedItemdatum",
            foreignKey: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.unitload",
        schema: "public",
        table: "unitload",
        source: "generator",
        details: {
            as: "relatedUnitload",
            foreignKey: "unitload",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedItemdatum",
            foreignKey: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.unitload",
        schema: "public",
        table: "unitload",
        source: "generator",
        details: {
            as: "relatedUnitload",
            foreignKey: "unitload",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};