/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'clientes.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'clientes.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./clientes.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("clidirIdcliFkeys").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.clientes",
    options: {
        tableName: "clientes",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "clientes_pkey"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        },
        "cuit": {
            type: Seq.CHAR(13),
            field: "cuit"
        },
        "dir": {
            type: Seq.CHAR(50),
            field: "dir"
        },
        "loc": {
            type: Seq.CHAR(30),
            field: "loc"
        },
        "codpos": {
            type: Seq.CHAR(8),
            field: "codpos"
        },
        "prov": {
            type: Seq.INTEGER,
            field: "prov"
        },
        "tel": {
            type: Seq.CHAR(50),
            field: "tel"
        },
        "vend": {
            type: Seq.INTEGER,
            field: "vend"
        },
        "codfac": {
            type: Seq.INTEGER,
            field: "codfac",
            unique: "clientes_codfac_key"
        },
        "razonsoc": {
            type: Seq.CHAR(50),
            field: "razonsoc"
        },
        "blk": {
            type: Seq.INTEGER,
            field: "blk"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.clidir",
        schema: "public",
        table: "clidir",
        source: "generator",
        details: {
            as: "clidirIdcliFkeys",
            foreignKey: "idcli",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.cuadricula",
        schema: "public",
        table: "cuadricula",
        source: "generator",
        details: {
            as: "relatedClidirIdcliFkeyCuadriculas",
            foreignKey: "idcli",
            otherKey: "cuadricula",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.expresos",
        schema: "public",
        table: "expresos",
        source: "generator",
        details: {
            as: "relatedClidirIdcliFkeyExpresos",
            foreignKey: "idcli",
            otherKey: "expreso",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.provincia",
        schema: "public",
        table: "provincia",
        source: "generator",
        details: {
            as: "relatedClidirIdcliFkeyProvs",
            foreignKey: "idcli",
            otherKey: "prov",
            through: "clidir",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};