/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'color.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'color.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./color.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkItemdataColors").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.color",
    options: {
        tableName: "color",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "color_pkey"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        },
        "codigo": {
            type: Seq.CHAR(16),
            field: "codigo",
            unique: "codigo_color_uk"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "fkItemdataColors",
            foreignKey: "color",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "itemdataColorFkeys",
            foreignKey: "color",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.articulo",
        schema: "public",
        table: "articulo",
        source: "generator",
        details: {
            as: "relatedFkItemdataColorArticulos",
            foreignKey: "color",
            otherKey: "articulo",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.articulo",
        schema: "public",
        table: "articulo",
        source: "generator",
        details: {
            as: "relatedFkItemdataColorArticulos",
            foreignKey: "color",
            otherKey: "articulo",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.articulo",
        schema: "public",
        table: "articulo",
        source: "generator",
        details: {
            as: "relatedItemdataColorFkeyArticulos",
            foreignKey: "color",
            otherKey: "articulo",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.color",
        schema: "public",
        table: "color",
        source: "generator",
        details: {
            as: "relatedFkItemdataColorColors",
            foreignKey: "color",
            otherKey: "color",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.color",
        schema: "public",
        table: "color",
        source: "generator",
        details: {
            as: "relatedItemdataColorFkeyColors",
            foreignKey: "color",
            otherKey: "color",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.articulo",
        schema: "public",
        table: "articulo",
        source: "generator",
        details: {
            as: "relatedItemdataColorFkeyArticulos",
            foreignKey: "color",
            otherKey: "articulo",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};