/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'pedcabaut.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'pedcabaut.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./pedcabaut.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.pedcabaut",
    options: {
        tableName: "pedcabaut",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id"
        },
        "pedcabId": {
            type: Seq.INTEGER,
            field: "pedcab_id"
        },
        "dto": {
            type: Seq.INTEGER,
            field: "dto"
        },
        "est": {
            type: Seq.INTEGER,
            field: "est"
        },
        "fecha": {
            type: Seq.DATEONLY,
            field: "fecha"
        },
        "usr": {
            type: Seq.INTEGER,
            field: "usr"
        }
    },
    relations: []
};