/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ped_pen.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ped_pen.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ped_pen.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("articulo").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.pedPen",
    options: {
        tableName: "ped_pen",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "articulo": {
            type: Seq.INTEGER,
            field: "articulo"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        },
        "fem": {
            type: Seq.DATEONLY,
            field: "fem"
        },
        "itemdata": {
            type: Seq.INTEGER,
            field: "itemdata"
        },
        "canAut": {
            type: Seq.DECIMAL(8, 3),
            field: "can_aut"
        },
        "id": {
            type: Seq.INTEGER,
            field: "id"
        },
        "precio": {
            type: Seq.DECIMAL(9, 3),
            field: "precio"
        }
    },
    relations: []
};