/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'categ.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'categ.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./categ.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.categ",
    options: {
        tableName: "categ",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.CHAR(3),
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "categ_pkey"
        },
        "nom": {
            type: Seq.CHAR(30),
            field: "nom"
        }
    },
    relations: []
};