/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'loghistory.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'loghistory.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./loghistory.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.loghistory",
    options: {
        tableName: "loghistory",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "primarypk"
        },
        "usuario": {
            type: Seq.INTEGER,
            field: "usuario",
            allowNull: false
        },
        "suid": {
            type: Seq.INTEGER,
            field: "suid",
            allowNull: false
        },
        "uldes": {
            type: Seq.INTEGER,
            field: "uldes"
        },
        "ulori": {
            type: Seq.INTEGER,
            field: "ulori"
        },
        "fecha": {
            type: Seq.DATEONLY,
            field: "fecha"
        }
    },
    relations: []
};