/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'pedcab.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'pedcab.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./pedcab.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("peditmPedcabs").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.pedcab",
    options: {
        tableName: "pedcab",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "pedcak_pkey"
        },
        "nro": {
            type: Seq.INTEGER,
            field: "nro"
        },
        "fem": {
            type: Seq.DATEONLY,
            field: "fem"
        },
        "ven": {
            type: Seq.INTEGER,
            field: "ven",
            references: "public.vend",
            referencesKey: "ven"
        },
        "cli": {
            type: Seq.INTEGER,
            field: "cli"
        },
        "obsaut": {
            type: Seq.TEXT,
            field: "obsaut"
        },
        "obsdep": {
            type: Seq.TEXT,
            field: "obsdep"
        },
        "empresa": {
            type: Seq.INTEGER,
            field: "empresa"
        },
        "dto": {
            type: Seq.INTEGER,
            field: "dto"
        },
        "est": {
            type: Seq.INTEGER,
            field: "est"
        },
        "precio": {
            type: Seq.DECIMAL(9, 3),
            field: "precio",
            allowNull: false
        },
        "articulo": {
            type: Seq.INTEGER,
            field: "articulo",
            allowNull: false
        },
        "cantot": {
            type: Seq.DECIMAL(8, 3),
            field: "cantot"
        },
        "mon": {
            type: Seq.INTEGER,
            field: "mon"
        },
        "cuadricula": {
            type: Seq.INTEGER,
            field: "cuadricula"
        },
        "fecent": {
            type: Seq.DATEONLY,
            field: "fecent"
        },
        "clidir": {
            type: Seq.INTEGER,
            field: "clidir"
        },
        "conven": {
            type: Seq.CHAR(50),
            field: "conven"
        },
        "endosoNro": {
            type: Seq.INTEGER,
            field: "endoso_nro"
        },
        "endosado": {
            type: Seq.INTEGER,
            field: "endosado"
        },
        "idPack": {
            type: Seq.INTEGER,
            field: "id_pack"
        },
        "tsId": {
            type: Seq.CHAR(18),
            field: "ts_id",
            unique: "pedcab_ts_id_key"
        },
        "prioridad": {
            type: Seq.INTEGER,
            field: "prioridad"
        },
        "hora": {
            type: Seq.DATE,
            field: "hora"
        },
        "urgencia": {
            type: Seq.INTEGER,
            field: "urgencia"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.peditm",
        schema: "public",
        table: "peditm",
        source: "generator",
        details: {
            as: "peditmPedcabs",
            foreignKey: "pedcab_id",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.vend",
        schema: "public",
        table: "vend",
        source: "generator",
        details: {
            as: "relatedVen",
            foreignKey: "ven",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};