/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'nuevo_art_col_vw.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'nuevo_art_col_vw.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./nuevo_art_col_vw.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("ncodart").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.nuevoArtColVw",
    options: {
        tableName: "nuevo_art_col_vw",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "ncodart": {
            type: Seq.CHAR(16),
            field: "ncodart"
        },
        "nnomart": {
            type: Seq.CHAR(50),
            field: "nnomart"
        },
        "ncodcol": {
            type: Seq.CHAR(16),
            field: "ncodcol"
        },
        "nnomcol": {
            type: Seq.CHAR(50),
            field: "nnomcol"
        },
        "id": {
            type: Seq.INTEGER,
            field: "id"
        }
    },
    relations: []
};