/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'calle.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'calle.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./calle.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("storagelocationCalles").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.calle",
    options: {
        tableName: "calle",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "calle_pkey"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        },
        "nave": {
            type: Seq.CHAR(5),
            field: "nave"
        },
        "orden": {
            type: Seq.INTEGER,
            field: "orden"
        },
        "deposito": {
            type: Seq.INTEGER,
            field: "deposito"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.storagelocation",
        schema: "public",
        table: "storagelocation",
        source: "generator",
        details: {
            as: "storagelocationCalles",
            foreignKey: "calle",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.area",
        schema: "public",
        table: "area",
        source: "generator",
        details: {
            as: "relatedStoragelocationCalleAreas",
            foreignKey: "calle",
            otherKey: "area",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.deposito",
        schema: "public",
        table: "deposito",
        source: "generator",
        details: {
            as: "relatedStoragelocationCalleDepositos",
            foreignKey: "calle",
            otherKey: "deposito",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.zona",
        schema: "public",
        table: "zona",
        source: "generator",
        details: {
            as: "relatedStoragelocationCalleZonas",
            foreignKey: "calle",
            otherKey: "zona",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.area",
        schema: "public",
        table: "area",
        source: "generator",
        details: {
            as: "relatedStoragelocationCalleAreas",
            foreignKey: "calle",
            otherKey: "area",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.zona",
        schema: "public",
        table: "zona",
        source: "generator",
        details: {
            as: "relatedStoragelocationCalleZonas",
            foreignKey: "calle",
            otherKey: "zona",
            through: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};