/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'sql.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'sql.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./sql.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("s1").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.sql",
    options: {
        tableName: "sql",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "s1": {
            type: Seq.STRING(79),
            field: "s1"
        },
        "s2": {
            type: Seq.STRING(79),
            field: "s2"
        },
        "s3": {
            type: Seq.STRING(79),
            field: "s3"
        },
        "s4": {
            type: Seq.STRING(79),
            field: "s4"
        },
        "s5": {
            type: Seq.STRING(79),
            field: "s5"
        },
        "s6": {
            type: Seq.STRING(79),
            field: "s6"
        },
        "s7": {
            type: Seq.STRING(79),
            field: "s7"
        },
        "s8": {
            type: Seq.STRING(79),
            field: "s8"
        },
        "s9": {
            type: Seq.STRING(79),
            field: "s9"
        },
        "s10": {
            type: Seq.STRING(79),
            field: "s10"
        },
        "s11": {
            type: Seq.STRING(79),
            field: "s11"
        },
        "s12": {
            type: Seq.STRING(79),
            field: "s12"
        }
    },
    relations: []
};