/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'unitload.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'unitload.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./unitload.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkStockunitUnitloads").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.unitload",
    options: {
        tableName: "unitload",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "unitload_pkey"
        },
        "unitloadtype": {
            type: Seq.INTEGER,
            field: "unitloadtype",
            comment: "0-Transitoria Disponible\n1-transitorias en uso\n2-moviles\n3-fijas\n\n"
        },
        "indice": {
            type: Seq.INTEGER,
            field: "indice"
        },
        "storagelocation": {
            type: Seq.INTEGER,
            field: "storagelocation",
            references: "public.storagelocation",
            referencesKey: "storagelocation"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.stockunit",
        schema: "public",
        table: "stockunit",
        source: "generator",
        details: {
            as: "fkStockunitUnitloads",
            foreignKey: "unitload",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.stockunit",
        schema: "public",
        table: "stockunit",
        source: "generator",
        details: {
            as: "stockunitUnitloadFkeys",
            foreignKey: "unitload",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.storagelocation",
        schema: "public",
        table: "storagelocation",
        source: "generator",
        details: {
            as: "relatedStoragelocation",
            foreignKey: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.storagelocation",
        schema: "public",
        table: "storagelocation",
        source: "generator",
        details: {
            as: "relatedStoragelocation",
            foreignKey: "storagelocation",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedFkStockunitUnitloadItemdata",
            foreignKey: "unitload",
            otherKey: "itemdata",
            through: "stockunit",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedFkStockunitUnitloadItemdata",
            foreignKey: "unitload",
            otherKey: "itemdata",
            through: "stockunit",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedStockunitUnitloadFkeyItemdata",
            foreignKey: "unitload",
            otherKey: "itemdata",
            through: "stockunit",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.unitload",
        schema: "public",
        table: "unitload",
        source: "generator",
        details: {
            as: "relatedFkStockunitUnitloadUnitloads",
            foreignKey: "unitload",
            otherKey: "unitload",
            through: "stockunit",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.unitload",
        schema: "public",
        table: "unitload",
        source: "generator",
        details: {
            as: "relatedStockunitUnitloadFkeyUnitloads",
            foreignKey: "unitload",
            otherKey: "unitload",
            through: "stockunit",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedStockunitUnitloadFkeyItemdata",
            foreignKey: "unitload",
            otherKey: "itemdata",
            through: "stockunit",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};