/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'vw_disponible_web.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'vw_disponible_web.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./vw_disponible_web.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("itemdata").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.vwDisponibleWeb",
    options: {
        tableName: "vw_disponible_web",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "itemdata": {
            type: Seq.INTEGER,
            field: "itemdata"
        },
        "codArt": {
            type: Seq.CHAR(16),
            field: "cod_art"
        },
        "nomArt": {
            type: Seq.CHAR(50),
            field: "nom_art"
        },
        "codCol": {
            type: Seq.CHAR(16),
            field: "cod_col"
        },
        "nomCol": {
            type: Seq.CHAR(50),
            field: "nom_col"
        },
        "now": {
            type: Seq.DATE,
            field: "now"
        }
    },
    relations: []
};