/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'packcab.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'packcab.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./packcab.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("packitmCabs").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.packcab",
    options: {
        tableName: "packcab",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "packcab_pkey"
        },
        "obs": {
            type: Seq.CHAR(50),
            field: "obs"
        },
        "idart": {
            type: Seq.INTEGER,
            field: "idart",
            allowNull: false,
            references: "public.articulo",
            referencesKey: "idart"
        },
        "empresa": {
            type: Seq.INTEGER,
            field: "empresa",
            allowNull: false,
            references: "public.empresa",
            referencesKey: "empresa"
        },
        "fem": {
            type: Seq.DATEONLY,
            field: "fem"
        },
        "festimada": {
            type: Seq.DATEONLY,
            field: "festimada"
        },
        "estado": {
            type: Seq.INTEGER,
            field: "estado"
        },
        "dep": {
            type: Seq.INTEGER,
            field: "dep"
        },
        "remId": {
            type: Seq.INTEGER,
            field: "rem_id"
        },
        "tipo": {
            type: Seq.INTEGER,
            field: "tipo",
            allowNull: false,
            comment: "si es packing o Devolucion a etiquetar\n1 - packing\n5 - Devoucion (como en remcab)"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.packitm",
        schema: "public",
        table: "packitm",
        source: "generator",
        details: {
            as: "packitmCabs",
            foreignKey: "packcab_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.packpza",
        schema: "public",
        table: "packpza",
        source: "generator",
        details: {
            as: "packpzaCabs",
            foreignKey: "packcab_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.articulo",
        schema: "public",
        table: "articulo",
        source: "generator",
        details: {
            as: "relatedIdart",
            foreignKey: "idart",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.empresa",
        schema: "public",
        table: "empresa",
        source: "generator",
        details: {
            as: "relatedEmpresa",
            foreignKey: "empresa",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedPackitmCabItemdata",
            foreignKey: "packcab_id",
            otherKey: "itemdata",
            through: "packitm",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedPackpzaCabItemdata",
            foreignKey: "packcab_id",
            otherKey: "itemdata",
            through: "packpza",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};