/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ctapencli.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ctapencli.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ctapencli.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.ctapencli",
    options: {
        tableName: "ctapencli",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "ctapencli_pkey",
            comment: "\n"
        },
        "cli": {
            type: Seq.INTEGER,
            field: "cli"
        },
        "nro": {
            type: Seq.INTEGER,
            field: "nro"
        },
        "tip": {
            type: Seq.INTEGER,
            field: "tip"
        },
        "tiptxt": {
            type: Seq.CHAR(3),
            field: "tiptxt"
        },
        "fem": {
            type: Seq.DATEONLY,
            field: "fem"
        },
        "fve": {
            type: Seq.DATEONLY,
            field: "fve"
        },
        "obs": {
            type: Seq.CHAR(50),
            field: "obs"
        },
        "itot": {
            type: Seq.FLOAT(24),
            field: "itot"
        },
        "ipen": {
            type: Seq.FLOAT(24),
            field: "ipen"
        },
        "est": {
            type: Seq.INTEGER,
            field: "est"
        }
    },
    relations: []
};