/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'remped.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'remped.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./remped.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.remped",
    options: {
        tableName: "remped",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "remped_pkey"
        },
        "remcabId": {
            type: Seq.INTEGER,
            field: "remcab_id"
        },
        "itemdata": {
            type: Seq.INTEGER,
            field: "itemdata"
        },
        "pzaPed": {
            type: Seq.INTEGER,
            field: "pza_ped"
        },
        "precio": {
            type: Seq.DECIMAL(15, 2),
            field: "precio"
        }
    },
    relations: []
};