/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'lote.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'lote.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./lote.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.lote",
    options: {
        tableName: "lote",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "lote_pkey"
        },
        "fecha": {
            type: Seq.DATEONLY,
            field: "fecha"
        },
        "usuario": {
            type: Seq.INTEGER,
            field: "usuario"
        },
        "obs": {
            type: Seq.CHAR(16),
            field: "obs"
        },
        "estado": {
            type: Seq.INTEGER,
            field: "estado"
        },
        "itemdata": {
            type: Seq.INTEGER,
            field: "itemdata"
        },
        "cant": {
            type: Seq.INTEGER,
            field: "cant"
        },
        "facnro": {
            type: Seq.CHAR(16),
            field: "facnro"
        },
        "nro": {
            type: Seq.INTEGER,
            field: "nro"
        },
        "priserie": {
            type: Seq.INTEGER,
            field: "priserie"
        }
    },
    relations: []
};