/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'remitm.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'remitm.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./remitm.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.remitm",
    options: {
        tableName: "remitm",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "remitm_pkey"
        },
        "idremcab": {
            type: Seq.INTEGER,
            field: "idremcab"
        },
        "idstockunit": {
            type: Seq.INTEGER,
            field: "idstockunit"
        }
    },
    relations: []
};