/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ssecur_pwdlog.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ssecur_pwdlog.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ssecur_pwdlog.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("nro").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.ssecurPwdlog",
    options: {
        tableName: "ssecur_pwdlog",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "nro": {
            type: Seq.INTEGER,
            field: "nro",
            primaryKey: true,
            allowNull: false,
            unique: "userkey"
        },
        "userno": {
            type: Seq.INTEGER,
            field: "userno",
            allowNull: false,
            unique: "userkey"
        },
        "pwpassword": {
            type: Seq.STRING(20),
            field: "pwpassword",
            allowNull: false
        },
        "pwdate": {
            type: Seq.INTEGER,
            field: "pwdate",
            unique: "userkey"
        },
        "pwtime": {
            type: Seq.INTEGER,
            field: "pwtime"
        }
    },
    relations: []
};