/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'remestado.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'remestado.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./remestado.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkRemestados").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.remestado",
    options: {
        tableName: "remestado",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "remestado_pkey"
        },
        "nom": {
            type: Seq.CHAR(15),
            field: "nom"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.remcabin",
        schema: "public",
        table: "remcabin",
        source: "generator",
        details: {
            as: "fkRemestados",
            foreignKey: "est",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};