/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'ped_pen_x_var.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'ped_pen_x_var.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./ped_pen_x_var.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("articulo").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.pedPenXVar",
    options: {
        tableName: "ped_pen_x_var",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "articulo": {
            type: Seq.INTEGER,
            field: "articulo"
        },
        "codigo": {
            type: Seq.CHAR(16),
            field: "codigo"
        },
        "id": {
            type: Seq.INTEGER,
            field: "id"
        },
        "sum": {
            type: Seq.DECIMAL,
            field: "sum"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        }
    },
    relations: []
};