/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'stksaldo.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'stksaldo.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./stksaldo.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedItemdatum").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.stksaldo",
    options: {
        tableName: "stksaldo",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "stksaldo_pkey"
        },
        "deposito": {
            type: Seq.INTEGER,
            field: "deposito"
        },
        "empresa": {
            type: Seq.INTEGER,
            field: "empresa"
        },
        "itemdata": {
            type: Seq.INTEGER,
            field: "itemdata",
            references: "public.itemdata",
            referencesKey: "itemdata"
        },
        "cantpza": {
            type: Seq.INTEGER,
            field: "cantpza"
        },
        "amount": {
            type: Seq.INTEGER,
            field: "amount"
        },
        "rcanpza": {
            type: Seq.INTEGER,
            field: "rcanpza"
        },
        "ramount": {
            type: Seq.INTEGER,
            field: "ramount"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "relatedItemdatum",
            foreignKey: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};