/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'empresa.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'empresa.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./empresa.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("packcabEmps").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.empresa",
    options: {
        tableName: "empresa",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "empresa_pkey"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.packcab",
        schema: "public",
        table: "packcab",
        source: "generator",
        details: {
            as: "packcabEmps",
            foreignKey: "empresa",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.articulo",
        schema: "public",
        table: "articulo",
        source: "generator",
        details: {
            as: "relatedPackcabEmpIdarts",
            foreignKey: "empresa",
            otherKey: "idart",
            through: "packcab",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};