/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'articulo.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'articulo.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('server/models/index.js'),
    model   = require('./articulo.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkItemdataArticulos").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.articulo",
    options: {
        tableName: "articulo",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "articulo_pkey"
        },
        "nom": {
            type: Seq.CHAR(50),
            field: "nom"
        },
        "codigo": {
            type: Seq.CHAR(16),
            field: "codigo",
            unique: "codigo_articulo_uk"
        },
        "uni": {
            type: Seq.CHAR(3),
            field: "uni"
        },
        "codfac": {
            type: Seq.INTEGER,
            field: "codfac"
        },
        "empresa": {
            type: Seq.INTEGER,
            field: "empresa"
        },
        "estado": {
            type: Seq.INTEGER,
            field: "estado"
        },
        "nro": {
            type: Seq.INTEGER,
            field: "nro"
        },
        "nom2": {
            type: Seq.CHAR(20),
            field: "nom2"
        },
        "categ": {
            type: Seq.CHAR(3),
            field: "categ",
            allowNull: false
        },
        "canprom": {
            type: Seq.DECIMAL(8, 3),
            field: "canprom"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "fkItemdataArticulos",
            foreignKey: "articulo",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.itemdata",
        schema: "public",
        table: "itemdata",
        source: "generator",
        details: {
            as: "itemdataArticuloFkeys",
            foreignKey: "articulo",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.packcab",
        schema: "public",
        table: "packcab",
        source: "generator",
        details: {
            as: "packcabArts",
            foreignKey: "idart",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.color",
        schema: "public",
        table: "color",
        source: "generator",
        details: {
            as: "relatedFkItemdataArticuloColors",
            foreignKey: "articulo",
            otherKey: "color",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.articulo",
        schema: "public",
        table: "articulo",
        source: "generator",
        details: {
            as: "relatedFkItemdataArticuloArticulos",
            foreignKey: "articulo",
            otherKey: "articulo",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.articulo",
        schema: "public",
        table: "articulo",
        source: "generator",
        details: {
            as: "relatedItemdataArticuloFkeyArticulos",
            foreignKey: "articulo",
            otherKey: "articulo",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.color",
        schema: "public",
        table: "color",
        source: "generator",
        details: {
            as: "relatedItemdataArticuloFkeyColors",
            foreignKey: "articulo",
            otherKey: "color",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.color",
        schema: "public",
        table: "color",
        source: "generator",
        details: {
            as: "relatedFkItemdataArticuloColors",
            foreignKey: "articulo",
            otherKey: "color",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.color",
        schema: "public",
        table: "color",
        source: "generator",
        details: {
            as: "relatedItemdataArticuloFkeyColors",
            foreignKey: "articulo",
            otherKey: "color",
            through: "itemdata",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.empresa",
        schema: "public",
        table: "empresa",
        source: "generator",
        details: {
            as: "relatedPackcabArtEmpresas",
            foreignKey: "idart",
            otherKey: "empresa",
            through: "packcab",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};